server:
  port: 8080
spring:
  application:
    name: "ms_authentication"
  devtools:
    add-properties: false
  r2dbc:
    host: localhost
    port: 5432
    database: users
    schema: public
    username: postgres
    password: 1234
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
jwt:
  key: "c7bc40a8ff9288da6ca4934bafde214f4d1f234f731f82e22a0e2bd135db8102"
logging:
  level:
    org:
      springframework:
        r2dbc=DEBUG:
